### ISSUE TITLE
How to replace the logger?

### ISSUE THREAD

**Issue by klingtnet** [goftp/server#23]
The library exposes [`Logger`](https://github.com/goftp/server/blob/master/logger.go) but all `logger` fields are private and there is no `setLogger` or similar method.
How can I assign my own logging struct?

**Comment by lunny** [comment]
The description?

**Comment by klingtnet** [comment]
I've updated the issue description (see above), sorry for the confusion.

**Comment by klingtnet** [comment]
I've implemented a [pluggable logging backend](https://github.com/klingtnet/goftp) in the mean time and will open a pull request.
