### ISSUE TITLE
passiveListenIP will get a bad IP string

### ISSUE THREAD

**Issue by lichao2014** [goftp/server#25]
`func(conn *Conn) passiveListenIP() string {

    if len(conn.PublicIp()) > 0 {

        return conn.PublicIp()

    }

    return conn.conn.LocalAddr().String()

}`

If I do not set "PublicIp" for conn config,  the "passiveListenIP"  will get a bad IP string likes "ip:port". 
I think the correct code is:       conn.conn.LocalAddr().(*net.TCPAddr).IP.String().

**Comment by lunny** [comment]
Hi, could you send a PR?

**Comment by discobean** [comment]
I ran into this issue too, although mine was the other way, I was setting PublicIp and for things to work I had to attach a port to the variable, ie. `publicIP := "1.2.3.4:21"`

**Comment by lunny** [comment]
I think this has been resolved.
