### ISSUE TITLE
Reading username from the driver

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [goftp/server#6]
Hi :)

This is my first project with golang. I'm using your ftp server to provide a way to upload CSV files with user data to be synced with data in Postgres. I've written a driver that receives such data and it works well. Thing is, where these data end up depends on who logged on to the FTP server.

AFAICT, the only place this information is stored is in `conn.user` after a successful logon. I don't see how I would be able to get at that information from my driver without for example modifying `server/cmd.go` to send it along as an extra argument to `PutFile`, but then I'd be destroying the interface contract. Of course, this wouldn't matter in my particular example, but if at all possible, I'd like to avoid forking your project just to accomplish this.

Since I'm so new to golang, I'm wondering if I'm missing something obvious here, so I'm just putting this question out there to see what you think :)

Thanks for your time!

Daniel

**Comment by lunny** [comment]
Hi, 

I'm happy you like this project. I think we can change the driver's interface and add a new method Init(conn *Conn), and add a new method `LoginUser() string` for Conn so that driver can visit the login user name.

You are welcome.

Lunny

**Comment by DanielSmedegaardBuus** [comment]
Hi :)

That would be really cool! 👍 I actually just forked it, and started passing the username to every method in the driver. It'd be great if this info was accessible in your original code :)

Thanks!

**Comment by DanielSmedegaardBuus** [comment]
Hi again :)

After being busy with a different project, I'm now back on this one.

Am I being retarded here, or does that commit not help? I mean, I still can't see how I'd access `LoginUser()` and `IsLogin()` from the driver. These methods are on the connection that is created when a user logs in, and the driver is a member on that connection. So, to get to either method, I'd have to be able to access the parent of the driver (i.e. something like `Driver.parent.conn.LoginUser()`), which isn't possible?

Am I just being dumb?

Cheers :)
