### ISSUE TITLE
Implement APPE command

### ISSUE THREAD

**Issue by isavcic** [goftp/server#72]
Since goftp doesn't support `APPE` command, some clients, namely libcurl and programs which use it, cannot perform the upload.

Can you please implement APPE instead of returning `202 Obsolete`?

Thanks

**Comment by isavcic** [comment]
I've encountered this with dar archiver which hangs on FTP upload.

**Comment by lunny** [comment]
@isavcic could you confirm that #73 fix this?

**Comment by isavcic** [comment]
@lunny looking good at the first glance! Sorry, I'll have to investigate a bit further, because I'm still seeing issues (though probably unrelated to this one) in DAR -> rclone with goftp server -> B2 pipeline.

**Comment by lunny** [comment]
@isavcic  I just merged #73 and if you have any problem feel free to reopen this.
